-- Customer account, wishlist, address book and realtime analytics support.
-- Run this after supabase/schema.sql in Supabase SQL Editor.

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text,
  full_name text,
  phone text,
  city text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.customer_addresses (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  title text not null default 'Основной адрес',
  city text not null,
  address text not null,
  is_default boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.wishlist_items (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  product_id bigint not null references public.products(id) on delete cascade,
  created_at timestamptz not null default now(),
  unique(user_id, product_id)
);

alter table public.customers add column if not exists user_id uuid references auth.users(id) on delete set null;
alter table public.orders add column if not exists user_id uuid references auth.users(id) on delete set null;

create index if not exists idx_profiles_email on public.profiles(email);
create index if not exists idx_customer_addresses_user_id on public.customer_addresses(user_id);
create index if not exists idx_wishlist_items_user_id on public.wishlist_items(user_id);
create index if not exists idx_wishlist_items_product_id on public.wishlist_items(product_id);
create index if not exists idx_orders_user_id on public.orders(user_id);
create index if not exists idx_customers_user_id on public.customers(user_id);

drop trigger if exists trg_profiles_updated_at on public.profiles;
create trigger trg_profiles_updated_at before update on public.profiles for each row execute function public.set_updated_at();

drop trigger if exists trg_customer_addresses_updated_at on public.customer_addresses;
create trigger trg_customer_addresses_updated_at before update on public.customer_addresses for each row execute function public.set_updated_at();

create or replace function public.handle_new_user_profile()
returns trigger language plpgsql security definer set search_path = public as $$
begin
  insert into public.profiles (id, email, full_name)
  values (new.id, new.email, coalesce(new.raw_user_meta_data->>'full_name', ''))
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created_create_profile on auth.users;
create trigger on_auth_user_created_create_profile
  after insert on auth.users
  for each row execute function public.handle_new_user_profile();

alter table public.profiles enable row level security;
alter table public.customer_addresses enable row level security;
alter table public.wishlist_items enable row level security;

drop policy if exists "Users can read own profile" on public.profiles;
create policy "Users can read own profile" on public.profiles for select to authenticated using (auth.uid() = id);

drop policy if exists "Users can update own profile" on public.profiles;
create policy "Users can update own profile" on public.profiles for update to authenticated using (auth.uid() = id) with check (auth.uid() = id);

drop policy if exists "Users can insert own profile" on public.profiles;
create policy "Users can insert own profile" on public.profiles for insert to authenticated with check (auth.uid() = id);

drop policy if exists "Users can read own addresses" on public.customer_addresses;
create policy "Users can read own addresses" on public.customer_addresses for select to authenticated using (auth.uid() = user_id);

drop policy if exists "Users can insert own addresses" on public.customer_addresses;
create policy "Users can insert own addresses" on public.customer_addresses for insert to authenticated with check (auth.uid() = user_id);

drop policy if exists "Users can update own addresses" on public.customer_addresses;
create policy "Users can update own addresses" on public.customer_addresses for update to authenticated using (auth.uid() = user_id) with check (auth.uid() = user_id);

drop policy if exists "Users can delete own addresses" on public.customer_addresses;
create policy "Users can delete own addresses" on public.customer_addresses for delete to authenticated using (auth.uid() = user_id);

drop policy if exists "Users can read own wishlist" on public.wishlist_items;
create policy "Users can read own wishlist" on public.wishlist_items for select to authenticated using (auth.uid() = user_id);

drop policy if exists "Users can insert own wishlist" on public.wishlist_items;
create policy "Users can insert own wishlist" on public.wishlist_items for insert to authenticated with check (auth.uid() = user_id);

drop policy if exists "Users can delete own wishlist" on public.wishlist_items;
create policy "Users can delete own wishlist" on public.wishlist_items for delete to authenticated using (auth.uid() = user_id);

-- Allow authenticated customers to see only their own orders/order items.
drop policy if exists "Users can read own orders" on public.orders;
create policy "Users can read own orders" on public.orders for select to authenticated using (auth.uid() = user_id);

drop policy if exists "Users can read own order items" on public.order_items;
create policy "Users can read own order items" on public.order_items for select to authenticated using (
  exists (select 1 from public.orders o where o.id = order_items.order_id and o.user_id = auth.uid())
);

-- Realtime for admin dashboards. Safe to run repeatedly.
do $$
begin
  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'orders'
  ) then
    alter publication supabase_realtime add table public.orders;
  end if;

  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'order_items'
  ) then
    alter publication supabase_realtime add table public.order_items;
  end if;
end $$;
