-- thrtythr.shop Supabase schema
-- Run this file in Supabase SQL Editor.

create extension if not exists pgcrypto;

create table if not exists public.categories (
  id bigint generated by default as identity primary key,
  name_ru text not null,
  name_kz text not null,
  slug text not null unique,
  description_ru text,
  description_kz text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.products (
  id bigint generated by default as identity primary key,
  slug text not null unique,
  name_ru text not null,
  name_kz text not null,
  description_ru text,
  description_kz text,
  price numeric(12,2) not null default 0,
  compare_at_price numeric(12,2),
  category_id bigint references public.categories(id) on delete set null,
  sub_category_ru text,
  sub_category_kz text,
  rating numeric(3,2) not null default 4.8,
  main_image text,
  stock integer not null default 0,
  status text not null default 'active' check (status in ('active','draft','archived')),
  is_featured boolean not null default false,
  is_bestseller boolean not null default false,
  is_new boolean not null default false,
  discount_percent integer not null default 0 check (discount_percent >= 0 and discount_percent <= 100),
  deleted_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.product_images (
  id bigint generated by default as identity primary key,
  product_id bigint not null references public.products(id) on delete cascade,
  image_url text not null,
  alt_ru text,
  alt_kz text,
  sort_order integer not null default 0,
  created_at timestamptz not null default now()
);

create table if not exists public.product_sizes (
  id bigint generated by default as identity primary key,
  product_id bigint not null references public.products(id) on delete cascade,
  size text not null,
  stock integer not null default 0,
  created_at timestamptz not null default now(),
  unique(product_id, size)
);

create table if not exists public.customers (
  id bigint generated by default as identity primary key,
  name text not null,
  phone text not null,
  email text,
  created_at timestamptz not null default now()
);

create table if not exists public.orders (
  id bigint generated by default as identity primary key,
  order_number text not null unique,
  customer_id bigint references public.customers(id) on delete set null,
  customer_name text not null,
  phone text not null,
  email text,
  city text not null,
  address text not null,
  comment text,
  total numeric(12,2) not null default 0,
  delivery_method text not null default 'courier',
  payment_method text not null default 'cash_on_delivery',
  payment_status text not null default 'pending' check (payment_status in ('pending','paid','failed','refunded')),
  order_status text not null default 'new' check (order_status in ('new','processing','shipped','delivered','canceled')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.order_items (
  id bigint generated by default as identity primary key,
  order_id bigint not null references public.orders(id) on delete cascade,
  product_id bigint references public.products(id) on delete set null,
  product_name text not null,
  size text,
  quantity integer not null default 1,
  price numeric(12,2) not null default 0,
  image text,
  created_at timestamptz not null default now()
);

create index if not exists idx_products_status on public.products(status);
create index if not exists idx_products_flags on public.products(is_featured, is_bestseller, is_new);
create index if not exists idx_products_category_id on public.products(category_id);
create index if not exists idx_product_images_product_id on public.product_images(product_id);
create index if not exists idx_product_sizes_product_id on public.product_sizes(product_id);
create index if not exists idx_orders_created_at on public.orders(created_at desc);
create index if not exists idx_orders_status on public.orders(order_status, payment_status);

create or replace function public.set_updated_at()
returns trigger language plpgsql as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_categories_updated_at on public.categories;
create trigger trg_categories_updated_at before update on public.categories for each row execute function public.set_updated_at();

drop trigger if exists trg_products_updated_at on public.products;
create trigger trg_products_updated_at before update on public.products for each row execute function public.set_updated_at();

drop trigger if exists trg_orders_updated_at on public.orders;
create trigger trg_orders_updated_at before update on public.orders for each row execute function public.set_updated_at();

alter table public.categories enable row level security;
alter table public.products enable row level security;
alter table public.product_images enable row level security;
alter table public.product_sizes enable row level security;
alter table public.customers enable row level security;
alter table public.orders enable row level security;
alter table public.order_items enable row level security;

drop policy if exists "Public can read categories" on public.categories;
create policy "Public can read categories" on public.categories for select using (true);

drop policy if exists "Public can read active products" on public.products;
create policy "Public can read active products" on public.products for select using (status = 'active' and deleted_at is null);

drop policy if exists "Public can read product images" on public.product_images;
create policy "Public can read product images" on public.product_images for select using (true);

drop policy if exists "Public can read product sizes" on public.product_sizes;
create policy "Public can read product sizes" on public.product_sizes for select using (true);

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('products', 'products', true, 10485760, array['image/jpeg','image/png','image/webp','image/gif'])
on conflict (id) do update set public = true, file_size_limit = 10485760, allowed_mime_types = array['image/jpeg','image/png','image/webp','image/gif'];

drop policy if exists "Public can read product files" on storage.objects;
create policy "Public can read product files" on storage.objects for select using (bucket_id = 'products');

-- Service role key is used by server-side admin routes and bypasses RLS.

insert into public.categories (name_ru, name_kz, slug, description_ru, description_kz) values
('Одежда', 'Киім', 'apparel', 'Футболки, худи, лонгсливы и брюки', 'Футболкалар, худилер, лонгсливтер және шалбар'),
('Обувь', 'Аяқ киім', 'footwear', 'Кроссовки и кеды', 'Кроссовкалар және кедтер'),
('Аксессуары', 'Аксессуарлар', 'accessories', 'Сумки, украшения и аксессуары', 'Сөмкелер, әшекейлер және аксессуарлар')
on conflict (slug) do update set name_ru = excluded.name_ru, name_kz = excluded.name_kz, description_ru = excluded.description_ru, description_kz = excluded.description_kz;

with cats as (select id, slug from public.categories), seed_products as (
  select * from (values
    ('vans-tote-white','Vans Off The Wall Tote White','Vans Off The Wall Tote White','Повседневная сумка Vans Off The Wall для города и учебы.','Қалаға және оқуға арналған Vans Off The Wall сөмкесі.',24000,null,'accessories','Сумки','Сөмкелер','https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&q=80&w=1200',12,true,true,true),
    ('vans-tote-black','Vans Off The Wall Tote Black','Vans Off The Wall Tote Black','Черная сумка Vans с контрастным принтом.','Контраст принті бар қара Vans сөмкесі.',24000,null,'accessories','Сумки','Сөмкелер','https://images.unsplash.com/photo-1594223274512-ad4803739b7c?auto=format&fit=crop&q=80&w=1200',10,true,true,true),
    ('melancholy-longsleeve','Melancholy Black Longsleeve','Melancholy Black Longsleeve','Черный лонгслив с графикой в темной эстетике.','Қара эстетикадағы графикасы бар қара лонгслив.',32000,null,'apparel','Лонгсливы','Лонгсливтер','https://images.unsplash.com/photo-1556821840-3a63f95609a7?auto=format&fit=crop&q=80&w=1200',16,true,true,true),
    ('black-eye-graphic-tee','Black Eye Graphic Tee','Black Eye Graphic Tee','Футболка с крупным графическим принтом.','Үлкен графикалық принті бар футболка.',28000,null,'apparel','Футболки','Футболкалар','https://images.unsplash.com/photo-1576566582419-43c329864205?auto=format&fit=crop&q=80&w=1200',16,true,true,true),
    ('cyrillic-graphic-tee','Color Cyrillic Graphic Tee','Color Cyrillic Graphic Tee','Футболка с цветной кириллической графикой.','Түрлі-түсті кирилл графикасы бар футболка.',30000,null,'apparel','Футболки','Футболкалар','https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?auto=format&fit=crop&q=80&w=1200',16,true,false,true),
    ('vans-knu-skool-black','Vans Knu Skool Black','Vans Knu Skool Black','Черные кеды Vans в скейт-силуэте.','Скейт силуэтіндегі қара Vans кедтері.',52000,null,'footwear','Кеды','Кедтер','https://images.unsplash.com/photo-1525966222134-fcfa99bafb73?auto=format&fit=crop&q=80&w=1200',12,true,true,false),
    ('opium-boxy-tee','Opium Boxy Tee','Opium Boxy Tee','Бокс-футболка свободного кроя.','Еркін пішімді boxy футболка.',22000,null,'apparel','Футболки','Футболкалар','https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?auto=format&fit=crop&q=80&w=1200',16,false,false,true),
    ('black-nylon-crossbody','Black Nylon Crossbody','Black Nylon Crossbody','Нейлоновая сумка через плечо.','Иыққа асатын нейлон сөмке.',59000,null,'accessories','Сумки','Сөмкелер','https://images.unsplash.com/photo-1594223274512-ad4803739b7c?auto=format&fit=crop&q=80&w=1200',9,true,false,false),
    ('rick-owens-jumbo-lace','Rick Owens Jumbo Lace','Rick Owens Jumbo Lace','Архивная обувь с темной эстетикой.','Қара эстетикадағы архивтік аяқ киім.',450000,null,'footwear','Кроссовки','Кроссовкалар','https://images.unsplash.com/photo-1628149422079-0efc0683a311?auto=format&fit=crop&q=80&w=1200',12,true,true,false),
    ('balenciaga-defender','Balenciaga Defender','Balenciaga Defender','Массивный силуэт для выразительного образа.','Айқын образға арналған көлемді силуэт.',580000,null,'footwear','Кроссовки','Кроссовкалар','https://images.unsplash.com/photo-1615291244093-68f7000d11c1?auto=format&fit=crop&q=80&w=1200',12,true,true,false),
    ('distressed-baggy-denim','Distressed Baggy Denim','Distressed Baggy Denim','Широкие джинсы с потертостями.','Тозған эффектісі бар кең джинсы.',48000,null,'apparel','Деним','Деним','https://images.unsplash.com/photo-1624378439575-d8705ad7ae80?auto=format&fit=crop&q=80&w=1200',16,false,false,true),
    ('silver-chain-bracelet','Silver Chain Bracelet','Silver Chain Bracelet','Серебристый браслет-цепь.','Күміс түсті тізбек білезік.',39000,null,'accessories','Украшения','Әшекейлер','https://images.unsplash.com/photo-1611591437281-460bfbe1220a?auto=format&fit=crop&q=80&w=1200',8,false,false,true)
  ) as p(slug,name_ru,name_kz,description_ru,description_kz,price,compare_at_price,category_slug,sub_ru,sub_kz,img,stock,featured,bestseller,is_new)
)
insert into public.products (slug, name_ru, name_kz, description_ru, description_kz, price, compare_at_price, category_id, sub_category_ru, sub_category_kz, main_image, stock, status, is_featured, is_bestseller, is_new)
select p.slug, p.name_ru, p.name_kz, p.description_ru, p.description_kz, p.price, p.compare_at_price, c.id, p.sub_ru, p.sub_kz, p.img, p.stock, 'active', p.featured, p.bestseller, p.is_new
from seed_products p join cats c on c.slug = p.category_slug
on conflict (slug) do update set name_ru = excluded.name_ru, name_kz = excluded.name_kz, description_ru = excluded.description_ru, description_kz = excluded.description_kz, price = excluded.price, category_id = excluded.category_id, sub_category_ru = excluded.sub_category_ru, sub_category_kz = excluded.sub_category_kz, main_image = excluded.main_image, stock = excluded.stock, status = 'active', is_featured = excluded.is_featured, is_bestseller = excluded.is_bestseller, is_new = excluded.is_new;

insert into public.product_images (product_id, image_url, alt_ru, alt_kz, sort_order)
select p.id, p.main_image, p.name_ru, p.name_kz, 0 from public.products p
where not exists (select 1 from public.product_images i where i.product_id = p.id and i.sort_order = 0);

insert into public.product_sizes (product_id, size, stock)
select p.id, s.size, 4
from public.products p
cross join lateral (select unnest(case when p.category_id = (select id from public.categories where slug = 'footwear') then array['39','40','41','42','43','44'] when p.category_id = (select id from public.categories where slug = 'accessories') then array['OS'] else array['S','M','L','XL'] end) as size) s
on conflict (product_id, size) do nothing;
