import type { Product } from '@/lib/types';

const img = 'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?auto=format&fit=crop&q=80&w=1200';

export const fallbackProducts: Product[] = [
  { id: 1, slug: 'vans-tote-white', name: 'Vans Off The Wall Tote White', price: 24000, compare_at_price: null, category_id: 3, category_name: 'Аксессуары', category_slug: 'accessories', sub_category: 'Сумки', rating: 4.8, description: 'Повседневная сумка Vans Off The Wall для города и учебы.', main_image: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&q=80&w=1200', image_url: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&q=80&w=1200', stock: 12, status: 'active', is_featured: true, is_bestseller: true, is_new: true, discount_percent: 0, images: [], sizes: [{ id: 1, product_id: 1, size: 'OS', stock: 12 }] },
  { id: 2, slug: 'vans-tote-black', name: 'Vans Off The Wall Tote Black', price: 24000, compare_at_price: null, category_id: 3, category_name: 'Аксессуары', category_slug: 'accessories', sub_category: 'Сумки', rating: 4.7, description: 'Черная сумка Vans с контрастным принтом.', main_image: 'https://images.unsplash.com/photo-1594223274512-ad4803739b7c?auto=format&fit=crop&q=80&w=1200', image_url: 'https://images.unsplash.com/photo-1594223274512-ad4803739b7c?auto=format&fit=crop&q=80&w=1200', stock: 10, status: 'active', is_featured: true, is_bestseller: true, is_new: true, discount_percent: 0, images: [], sizes: [{ id: 2, product_id: 2, size: 'OS', stock: 10 }] },
  { id: 3, slug: 'melancholy-longsleeve', name: 'Melancholy Black Longsleeve', price: 32000, compare_at_price: null, category_id: 1, category_name: 'Одежда', category_slug: 'apparel', sub_category: 'Лонгсливы', rating: 4.9, description: 'Черный лонгслив с графикой в темной эстетике.', main_image: 'https://images.unsplash.com/photo-1556821840-3a63f95609a7?auto=format&fit=crop&q=80&w=1200', image_url: 'https://images.unsplash.com/photo-1556821840-3a63f95609a7?auto=format&fit=crop&q=80&w=1200', stock: 16, status: 'active', is_featured: true, is_bestseller: true, is_new: true, discount_percent: 0, images: [], sizes: ['S','M','L','XL'].map((size, index) => ({ id: 30 + index, product_id: 3, size, stock: 4 })) },
  { id: 4, slug: 'black-eye-graphic-tee', name: 'Black Eye Graphic Tee', price: 28000, compare_at_price: null, category_id: 1, category_name: 'Одежда', category_slug: 'apparel', sub_category: 'Футболки', rating: 4.8, description: 'Футболка с крупным графическим принтом.', main_image: 'https://images.unsplash.com/photo-1576566582419-43c329864205?auto=format&fit=crop&q=80&w=1200', image_url: 'https://images.unsplash.com/photo-1576566582419-43c329864205?auto=format&fit=crop&q=80&w=1200', stock: 16, status: 'active', is_featured: true, is_bestseller: true, is_new: true, discount_percent: 0, images: [], sizes: ['S','M','L','XL'].map((size, index) => ({ id: 40 + index, product_id: 4, size, stock: 4 })) },
  { id: 5, slug: 'cyrillic-graphic-tee', name: 'Color Cyrillic Graphic Tee', price: 30000, compare_at_price: null, category_id: 1, category_name: 'Одежда', category_slug: 'apparel', sub_category: 'Футболки', rating: 4.7, description: 'Футболка с цветной кириллической графикой.', main_image: 'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?auto=format&fit=crop&q=80&w=1200', image_url: 'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?auto=format&fit=crop&q=80&w=1200', stock: 16, status: 'active', is_featured: true, is_bestseller: false, is_new: true, discount_percent: 0, images: [], sizes: ['S','M','L','XL'].map((size, index) => ({ id: 50 + index, product_id: 5, size, stock: 4 })) },
  { id: 6, slug: 'vans-knu-skool-black', name: 'Vans Knu Skool Black', price: 52000, compare_at_price: null, category_id: 2, category_name: 'Обувь', category_slug: 'footwear', sub_category: 'Кеды', rating: 4.7, description: 'Черные кеды Vans в скейт-силуэте.', main_image: 'https://images.unsplash.com/photo-1525966222134-fcfa99bafb73?auto=format&fit=crop&q=80&w=1200', image_url: 'https://images.unsplash.com/photo-1525966222134-fcfa99bafb73?auto=format&fit=crop&q=80&w=1200', stock: 12, status: 'active', is_featured: true, is_bestseller: true, is_new: false, discount_percent: 0, images: [], sizes: ['39','40','41','42','43','44'].map((size, index) => ({ id: 60 + index, product_id: 6, size, stock: 2 })) },
  { id: 7, slug: 'opium-boxy-tee', name: 'Opium Boxy Tee', price: 22000, compare_at_price: null, category_id: 1, category_name: 'Одежда', category_slug: 'apparel', sub_category: 'Футболки', rating: 4.6, description: 'Бокс-футболка свободного кроя.', main_image: img, image_url: img, stock: 16, status: 'active', is_featured: false, is_bestseller: false, is_new: true, discount_percent: 0, images: [], sizes: ['S','M','L','XL'].map((size, index) => ({ id: 70 + index, product_id: 7, size, stock: 4 })) },
  { id: 8, slug: 'black-nylon-crossbody', name: 'Black Nylon Crossbody', price: 59000, compare_at_price: null, category_id: 3, category_name: 'Аксессуары', category_slug: 'accessories', sub_category: 'Сумки', rating: 4.7, description: 'Нейлоновая сумка через плечо.', main_image: 'https://images.unsplash.com/photo-1594223274512-ad4803739b7c?auto=format&fit=crop&q=80&w=1200', image_url: 'https://images.unsplash.com/photo-1594223274512-ad4803739b7c?auto=format&fit=crop&q=80&w=1200', stock: 9, status: 'active', is_featured: true, is_bestseller: false, is_new: false, discount_percent: 0, images: [], sizes: [{ id: 8, product_id: 8, size: 'OS', stock: 9 }] },
];
